Implement view movie in isolation and respective tests
RileyRetzloff/Group-5-itsc-3155-module-9-assignment pull request #4
Opened 2023-10-25 21:53 UTC by TemboJembo

2023-10-25 23:56 UTC, RileyRetzloff commented on templates/get_single_movie.html
> +    <form action='/movies/{{movie.movie_id}}/edit' method="get">
I'm not sure but do the buttons need a 'name' attribute so the values from them can be read in? Also might be good to add some Bootstrap button styling on both buttons. 
<img width="738" alt="image" src="https://github.com/RileyRetzloff/Group-5-itsc-3155-module-9-assignment/assets/143763088/0e344da4-192b-4487-a263-07513b053f80">

2023-10-25 23:56 UTC, RileyRetzloff commented on tests/e2e/test_view_movie_page.py
LGTM

2023-10-25 23:56 UTC, RileyRetzloff commented on tests/unit/test_get_movie_by_id.py
LGTM

2023-10-25 23:58 UTC, RileyRetzloff commented on app.py
LGTM

2023-10-26 00:03 UTC, RileyRetzloff reviewed
Everything looks good to me except, and tbh I'm not 100% sure about this, I think you might want to add a 'name' attribute to the two buttons in your get_single_movie.html file so the values from the two buttons are usable. You also might wanna add some Bootstrap styling which should be really easy. The code in app.py and your e2e and unit tests looks great to me.

2023-10-26 01:53 UTC, AveryNewkirk requested changes
Make sure to fetch and merge all changes so you can link your feature to the project. Everything looks great but we cant merge this until there is a link.

2023-10-26 18:28 UTC, AveryNewkirk approved these changes
Looks great.

2023-10-26 18:28 UTC, merged